DROP DATABASE IF EXISTS nightlifeDB;

CREATE DATABASE IF NOT EXISTS nightlifeDB;
USE nightlifeDB;

CREATE TABLE IF NOT EXISTS clients
(

	ID 			INT(11) 		NOT NULL 		PRIMARY KEY AUTO_INCREMENT,
    name 		VARCHAR(125)	NOT NULL,
    lastname	VARCHAR(125)	NOT NULL,
    cellphone	VARCHAR(20)		DEFAULT NULL

)
ENGINE=INNODB
DEFAULT CHARSET=LATIN1;

CREATE TABLE IF NOT EXISTS employees
(

	ID			INT(11)			NOT NULL		PRIMARY KEY AUTO_INCREMENT,
	name 		VARCHAR(125)	NOT NULL,
    lastname	VARCHAR(125)	NOT NULL,
    cellphone	VARCHAR(20)		NOT NULL	

)
ENGINE=INNODB
DEFAULT CHARSET=LATIN1;

CREATE TABLE IF NOT EXISTS employee_access
(

	ID			INT(11)			NOT NULL		PRIMARY KEY AUTO_INCREMENT,
    FK_ID		INT(11)			NOT NULL,
    username	VARCHAR(45)		NOT NULL,
    pass		VARCHAR(21)		NOT NULL,
    permissions CHAR(3)			NOT NULL

)
ENGINE=INNODB
DEFAULT CHARSET=LATIN1;

ALTER TABLE employee_access ADD FOREIGN KEY (FK_ID) REFERENCES employees(ID);

CREATE TABLE IF NOT EXISTS n_tables
(

	ID			INT(11)			NOT NULL		PRIMARY KEY AUTO_INCREMENT,
    area		VARCHAR(75)		NOT NULL,
    capacity	INT(5)			NOT NULL,
    status		BOOLEAN			DEFAULT FALSE

)
ENGINE=INNODB
DEFAULT CHARSET=LATIN1;

CREATE TABLE IF NOT EXISTS reserves
(

	ID				INT(11)			NOT NULL		PRIMARY KEY AUTO_INCREMENT,
    dtime_reserve	DATETIME		NOT NULL,
    FK_ID_table		INT(11)			NOT NULL,
	FK_ID_client	INT(11)			NOT NULL
    
)
ENGINE=INNODB
DEFAULT CHARSET=LATIN1;

CREATE TABLE IF NOT EXISTS p_alcohol
(

	ID				INT(11)			NOT NULL		PRIMARY KEY AUTO_INCREMENT,
    name			VARCHAR(255)	NOT NULL,
    price			DOUBLE			NOT NULL
	
)
ENGINE=INNODB
DEFAULT CHARSET=LATIN1;

CREATE TABLE IF NOT EXISTS p_meals
(

	ID				INT(11)			NOT NULL		PRIMARY KEY AUTO_INCREMENT,
    name			VARCHAR(255)	NOT NULL,
    price			DOUBLE			NOT NULL
	
)
ENGINE=INNODB
DEFAULT CHARSET=LATIN1;

CREATE TABLE IF NOT EXISTS p_misc
(

	ID				INT(11)			NOT NULL		PRIMARY KEY AUTO_INCREMENT,
    name			VARCHAR(255)	NOT NULL,
    price			DOUBLE			DEFAULT NULL
	
)
ENGINE=INNODB
DEFAULT CHARSET=LATIN1;

CREATE TABLE IF NOT EXISTS inventory
(

	FK_ID_alco		INT(11)			DEFAULT NULL,
	FK_ID_meals		INT(11)			DEFAULT NULL,
	FK_ID_misc		INT(11)			DEFAULT NULL,
	quantity		INT(11)			NOT NULL
	
)
ENGINE=INNODB
DEFAULT CHARSET=LATIN1;


CREATE TABLE IF NOT EXISTS orders
(

	ID				INT(11)			NOT NULL		PRIMARY KEY,
	FK_ID_alco		INT(11)			DEFAULT NULL,
	FK_ID_meals		INT(11)			DEFAULT NULL,
	FK_ID_misc		INT(11)			DEFAULT NULL,
	quantity		INT(11)			NOT NULL
	
)
ENGINE=INNODB
DEFAULT CHARSET=LATIN1;

CREATE TABLE IF NOT EXISTS sales
(

	ID				INT(11)			NOT NULL		PRIMARY KEY AUTO_INCREMENT,
    FK_ID_client	INT(11)			NOT NULL,
    FK_ID_employee	INT(11)			NOT NULL,
	FK_ID_table		INT(11)			NOT NULL,
    FK_ID_order		INT(11)			NOT NULL,
	entrance		DATETIME		NOT NULL,
    sale_date		DATETIME		NOT NULL,
    total			DOUBLE			NOT NULL

)
ENGINE=INNODB
DEFAULT CHARSET=LATIN1;